# Generated by Django 3.2.18 on 2023-06-13 14:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sum_of_salary', models.PositiveIntegerField(verbose_name='Сумма')),
                ('date_of_increase', models.DateField(auto_now_add=True, verbose_name='Дата повышения')),
                ('next_date_of_increase', models.DateField(verbose_name='Следующее повышение')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Работник')),
            ],
            options={
                'verbose_name': 'Зарплата',
                'verbose_name_plural': 'Список зарплат',
                'ordering': ('-date_of_increase',),
            },
        ),
    ]
