# Generated by Django 3.2.18 on 2023-06-14 04:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salary',
            name='is_actual',
            field=models.BooleanField(default=True, verbose_name='актуальность зп'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary', to=settings.AUTH_USER_MODEL, verbose_name='Работник'),
        ),
    ]
